language: node_js

node_js:
  - node
  - lts/8

cache:
  directories:
    - "node_modules"
  yarn: true

before_install:
  - yarn bootstrap

install:
  - travis_retry composer install

script:
  - yarn build
  - yarn test
