version: '2'
services:
  web-api:
    image: 315915642113.dkr.ecr.us-east-1.amazonaws.com/theia
    environment:
      NEW_RELIC_APP_NAME: theia
      ROLLBAR_ENV: production
      THEIA_SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/315915642113/TheiaReheatJobs
      THEIA_S3_BUCKET: coursehero
    stdin_open: true
    volumes:
      - /run/secrets/theia.id_rsa:/root/.ssh/id_rsa
      - /run/secrets/theia.known_hosts:/root/.ssh/known_hosts
      - /run/secrets/theia.aws.config/:/root/.aws/config
      - /run/secrets/theia.rollbar.token:/run/secrets/theia.rollbar.token
      - /run/secrets/theia.s3.bucket:/run/secrets/theia.s3.bucket
      - /run/secrets/theia.sqs.queue:/run/secrets/theia.sqs.queue
      - /run/secrets/aws.key:/run/secrets/aws.key
      - /run/secrets/aws.secret:/run/secrets/aws.secret
      - /run/secrets/api.authKey:/run/secrets/api.authKey
      - /run/secrets/slack.token:/run/secrets/slack.token
      - /run/secrets/newrelic.license:/run/secrets/newrelic.license
      - /var/rollbar:/var/rollbar
    tty: false
    #provide external links to services directly
#    external_links:
#      - external-service-name/container-name:how-i-want-to-talk-to-it.internal.coursehero.com
    logging:
      driver: awslogs
      options:
        awslogs-group: theia
        awslogs-region: us-east-1
        tag: 'theia-web-api-{{ with split .Name ":" }}{{join . "_"}}{{end}}-{{.ID}}'
    labels:
      io.rancher.container.pull_image: always
      traefik.enable: 'true'
      traefik.alias: theia
      traefik.port: '80'
      traefik.domain: internal.coursehero.com
  build:
    image: 315915642113.dkr.ecr.us-east-1.amazonaws.com/theia
    environment:
      NEW_RELIC_APP_NAME: theia
      ROLLBAR_ENV: production
      THEIA_SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/315915642113/TheiaReheatJobs
      THEIA_S3_BUCKET: coursehero
    stdin_open: true
    volumes:
      - /run/secrets/theia.id_rsa:/root/.ssh/id_rsa
      - /run/secrets/theia.known_hosts:/root/.ssh/known_hosts
      - /run/secrets/theia.aws.config/:/root/.aws/config
      - /run/secrets/theia.rollbar.token:/run/secrets/theia.rollbar.token
      - /run/secrets/theia.s3.bucket:/run/secrets/theia.s3.bucket
      - /run/secrets/theia.sqs.queue:/run/secrets/theia.sqs.queue
      - /run/secrets/aws.key:/run/secrets/aws.key
      - /run/secrets/aws.secret:/run/secrets/aws.secret
      - /run/secrets/api.authKey:/run/secrets/api.authKey
      - /run/secrets/slack.token:/run/secrets/slack.token
      - /run/secrets/newrelic.license:/run/secrets/newrelic.license
      - /var/rollbar:/var/rollbar
    tty: false
    logging:
      driver: awslogs
      options:
        awslogs-group: theia
        awslogs-region: us-east-1
        tag: 'theia-build-{{ with split .Name ":" }}{{join . "_"}}{{end}}-{{.ID}}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
      cron.schedule: '* * * * *'
    command: bash -c 'source ./secrets.sh && yarn run start-build'
