version: '2'
services:
  web-api:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 30000
      strategy: recreateOnQuorum
      request_line: GET "/heartbeat" "HTTP/1.0"
      reinitializing_timeout: 60000
